config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post 'send_welcome_email', to: 'user#send_welcome_email', as: :send_welcome_email
  resources :events do
    collection do
      get :view # Ruta personalizada para la acción view
    end
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  # validations

  validates :eventName, presence: true, length: { minimum: 3 }
  validates :level, presence: true,
                    inclusion: { in: %w[basic middle advance], message: "%<value>s isn't a correct level" }
  validates :descripcion, presence: true, length: { maximum: 500 }
  validates :date, presence: true

  self.table_name = 'event_infos'

  scope :by_level, ->(level) { where(level: level) if level.presence? }
  scope :by_exhibitor, ->(exhibitor) { where(exhibitor: exhibitor) if exhibitor.present? }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: { user: 'user', moderator: 'moderator', admin: 'admin' }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  after_create :send_welcome_email

  private

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def after_sign_in_path_for(resource)
    events_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[edit update show destroy]

  def index
    if params[:level].present?
      @events = Event.where(level: params[:level])
      @events = @events.by_exhibitor(params[:exhibitor]) if params[:exhibitor].present?
    else
      @events = Event.all
    end
  end

  def view
    @events = Event.all
  end

  def show
  end

  def edit
  end

  def new
    @event = Event.new
  end

  def create
    # Crea un nuevo evento asociado al usuario actual
    @event = current_user.events.build(events_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(events_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_path, status: :see_other, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def events_params
    params.require(:event).permit(:eventName, :descripcion, :level, :exhibitor, :date)
  end

  def set_event
    @event = Event.find(params[:id])
    return unless @event.nil?

    redirect_to events_path, alert: 'Event not found'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_event.html.erb
<div class="min-h-screen flex bg-gray-100" style="align-items:center;">
  <div id="<%= dom_id event %>" class="p-6 bg-white shadow-lg rounded-lg border border-gray-300 mb-6 max-w-md w-full mx-auto">
    <div class="bg-indigo-500 text-white p-4 rounded-t-lg">
      <h2 class="text-xl font-bold">
        <%= event.eventName %>
      </h2>
    </div>

    <div class="p-4">
      <p class="text-gray-700 mb-2">
        <strong class="font-semibold text-gray-900">Exhibitor:</strong> <%= event.exhibitor %>
      </p>

      <p class="text-gray-700 mb-2">
        <strong class="font-semibold text-gray-900">Level:</strong> <%= event.level.capitalize %>
      </p>

      <p class="text-gray-700 mb-2">
        <strong class="font-semibold text-gray-900">Description:</strong> <%= event.descripcion %>
      </p>

      <p class="text-gray-700 mb-2">
        <strong class="font-semibold text-gray-900">Date:</strong> <%= event.date.strftime("%B %d, %Y") %>
      </p>
    </div>

 
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: @event) do |form| %>
  
  <% if @event.errors.any? %>
    <div class="bg-red-100 text-red-700 p-4 rounded mb-4">
      <h2 class="font-bold"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% @event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4" style="display: flex; flex-direction: column; width : 50%;">
    <%= form.label :eventName, class: "block text-gray-700 font-semibold" %>
    <%= form.text_field :eventName, class: "w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
  </div>

  <div class="mb-4" style="display: flex; flex-direction: column; width : 50%;">
    <%= form.label :exhibitor, class: "block text-gray-700 font-semibold" %>
    <%= form.text_field :exhibitor, class: "w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
  </div>

  <div class="mb-4" style="display: flex; flex-direction: column; width : 50%;">
    <%= form.label :level, class: "block text-gray-700 font-semibold" %>
    <%= form.text_field :level, class: "w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
  </div>

  <div class="mb-4" style="display: flex; flex-direction: column; width : 50%;">
    <%= form.label :descripcion, class: "block text-gray-700 font-semibold" %>
    <%= form.text_area :descripcion, class: "w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
  </div>

  <div class="mb-4" style="display: flex; flex-direction: column; width : 50%;">
    <%= form.label :date, class: "block text-gray-700 font-semibold" %>
    <%= form.date_field :date, class: "w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
  </div>

  <div class="mb-4">
    <%= form.submit "Save Event", class: "w-full bg-blue-500 text-white py-2 px-4 rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
  </div>

<% end %>

app/views/events/edit.html.erb
<h1 class="text-2xl font-bold text-center mb-6">Editing Event</h1>

<%= render "form", event: @event %>

<div class="text-center mt-4">
  <%= link_to "Show this event", @event, class: "text-blue-500 hover:text-blue-700 font-semibold mx-2" %>
  <%= link_to "Back to events", events_path, class: "text-blue-500 hover:text-blue-700 font-semibold mx-2" %>
</div>

app/views/events/index.html.erb
<%= link_to "Create a new event", new_event_path, class: "btn btn-primary" %>
<%= form_with url: events_path, method: :get, local: true, class: "bg-white p-6 rounded-lg shadow-md space-y-4 flex" do %>
  <div class="mb-4" style="margin: 15px 10px 0 10px;">
    <label for="level" class="block text-gray-700 font-semibold">Filter by level:</label>
    <%= select_tag :level, options_for_select([["Basic", "basic"], ["Middle", "middle"], ["Advanced", "advanced"]]), include_blank: true, class: "mt-1 block w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-300" %>
  </div>

  <div class="mb-4" style="margin: 15px 10px 0 10px;">
    <label for="exhibitor" class="block text-gray-700 font-semibold">Filter by exhibitor:</label>
    <%= select_tag :exhibitor, options_from_collection_for_select(Event.select(:exhibitor).distinct, :exhibitor, :exhibitor), include_blank: true, class: "mt-1 block w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-300" %>
  </div>

  <div class="text-right" style="margin: 15px 10px 0 10px;">
    <%= submit_tag "Filtrar", class: "px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
  </div>
<% end %>

<div class="space-y-6 mt-8">
  <% @events.each do |event| %>
    <div class="bg-white p-6 rounded-lg shadow-md">
      <h2 class="text-2xl font-bold text-gray-800"><%= event.eventName %></h2>
      <h5 class="text-gray-600"><%= event.exhibitor %></h5>
      <p class="text-gray-700 mt-2"><%= truncate(event.descripcion, length: 100) %>...</p>
      <p class="mt-4">
        <%= link_to "Show this event", event_path(event), class: "text-blue-500 hover:underline" %>
      </p>
    </div>
      
  <% end %>
  <%= button_to 'Cerrar sesión', destroy_user_session_path, method: :delete , class: "px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition" %>
</div>

app/views/events/new.html.erb
<h1>New event</h1>
<%= render "form", event: @event%>
<br>
<div>
    <%= link_to "Back to events", events_path%>
</div>

app/views/events/show.html.erb
<%= render @event %>

  <div class="mt-4">
<% if user_signed_in? && @event.user_id == current_user.id %>
  <%= link_to "Edit", edit_event_path(@event), class: "px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition duration-300 ease-in-out" %>
  <%= link_to "Delete", @event, method: :delete, data: { confirm: "Are you sure?" }, class: "px-4 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600 transition duration-300 ease-in-out ml-2" %>
  <%= link_to "Back to events", events_path, class: "btn btn-secondary mt-2" %>

<% else %>
  <%= link_to "Back to events", view_events_path, class: "btn btn-secondary mt-2" %>
<% end %>

  </div>
</div>

app/views/events/showView.html.erb
<%= render @event %>

app/views/events/view.html.erb
<div class="space-y-6 mt-8">
  <% @events.each do |event| %>
    <div class="bg-white p-6 rounded-lg shadow-md">
      <h2 class="text-2xl font-bold text-gray-800"><%= event.eventName %></h2>
      <h5 class="text-gray-600"><%= event.exhibitor %></h5>
      <p class="text-gray-700 mt-2"><%= truncate(event.descripcion, length: 100) %>...</p>
      <p class="mt-4">
        <%= link_to "Show this event", event_path(event), class: "text-blue-500 hover:underline" %>
      </p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Event" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% if user_signed_in? %>
<% end %>

  </body>
</html>